FROM mcr.microsoft.com/devcontainers/python:latest AS base

# Metadata indicating the maintainer of this Dockerfile
LABEL MAINTAINER="gvatsal60"
# Description of the purpose of this image
LABEL DESCRIPTION="Build Environment"

ARG USERNAME=vscode

# Install dependencies
RUN apt-get update \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Switch to non-root user
USER ${USERNAME}