# Compiler and flags

INC_DIR := inc
SRC_DIR := src
TEST_DIR := test/src

.PHONY: all build test clean

all: build

build:
	@echo "Building project..."

test:
	@echo "Building tests..."

run:
	@echo "Running project..."

clean:
	@echo "Cleaning project..."
